site_name: DeepExpressions

nav:
  - Home: index.md
  - PACKAGE:
    - FaceDetector: face_detector.md
    - Model: model.md
    - train_utils: 
      - DataLoader: train_utils/DataLoader.md
      - data_augmentation: train_utils/data_augmentation.md
    - wrapper: 
      - ImageDetector: wrapper/ImageDetector.md
      - VideoDetector: wrapper/VideoDetector.md

theme:
  name: readthedocs
